/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'hello_flutter';
  static const String PLUGIN_VERSION = '1.0.0+1';
}
