// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'hello_flutter';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ROBOTO_MEDIUM_12 = 'Roboto-Medium-12';
  static const String ROBOTO_REGULAR_14 = 'Roboto-Regular-14';
}
